addons:
  apt:
    packages:
    - sshpass

language: python
cache:
  - pip: true
  - directories:
    - state_data.json
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - nikola plugin --install deploy_hooks

script:
  - nikola build

deploy:
  skip_cleanup: true
  provider: script
  script: utils/deploy.sh
  on:
    branch: master
