addons:
  apt:
    packages:
    - sshpass

language: python
cache: pip
python:
  - "3.5"

install: "pip install -r requirements.txt"

script:
  - nikola build
  - nikola check -l -v

deploy:
  skip_cleanup: true
  provider: script
  script: utils/deploy.sh
  on:
    branch: master